trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: jfrog
  - name: MAVEN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.m2/repository



steps:

# Checkout code
- checkout: self

# Build using Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'
    mavenOptions: '-Xmx3072m'

# Upload JAR to JFrog Artifactory using curl
- script: |
    curl -u $(JFROG_USERNAME):$(JFROG_API_KEY) -T target/*.jar $(JFROG_URL)/$(JFROG_REPO)/spring-boot-hello-world/
  displayName: 'Upload to JFrog Artifactory'
