trigger:
- main

pool:
  name: 'Default'  # Self-hosted agent pool

variables:
  - group: jfrog
  - name: MAVEN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.m2/repository

steps:

# Checkout code
- checkout: self

# Build using Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    javaHomeOption: 'Path'
    jdkDirectory: '/usr/lib/jvm/java-17-openjdk-amd64'
    mavenOptions: '-Xmx3072m'

# Upload JAR to JFrog Artifactory (fully correct upload URL)
- script: |
    curl -v -u $(JFROG_USERNAME):$(JFROG_API_KEY) \
    -T target/*.jar \
    $(JFROG_URL)/local-libs-release/spring-boot-hello-world/
  displayName: 'Upload to JFrog Artifactory (Verbose)'
