trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  jarName: 'spring-boot-hello-world-0.0.1-SNAPSHOT.jar'
  remotePath: '/home/ec2-user/app'

stages:
- stage: Build
  displayName: 'Build JAR'
  jobs:
  - job: BuildJob
    steps:
    - checkout: self

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        options: '-DskipTests=true'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/target'
        Contents: '**/*.jar'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'

- stage: Deploy
  displayName: 'Deploy to EC2'
  dependsOn: Build
  jobs:
  - job: DeployJob
    steps:
    - download: current
      artifact: drop

    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'vm' # ✅ Your service connection name
        sourceFolder: '$(Pipeline.Workspace)/drop'
        contents: '**/*.jar'
        targetFolder: '$(remotePath)'

    - task: SSH@0
      inputs:
        sshEndpoint: 'vm'
        runOptions: 'commands'
        command: |
          cd $(remotePath)
          pkill -f $(jarName) || true
          nohup java -jar $(jarName) > app.log 2>&1 &
